# Environment Configuration Schema
# Defines the structure for environment configuration files (environments/*.yml)

$schema: "http://json-schema.org/draft-07/schema#"
title: "Environment Configuration"
description: "Configuration for benchmark execution environments"
type: object

required:
  - name
  - type
  - created_at

properties:
  name:
    type: string
    description: "Unique name for the environment"
    pattern: "^[a-zA-Z0-9_-]+$"
    minLength: 1
    maxLength: 50

  type:
    type: string
    description: "Environment type"
    enum: ["docker", "asdf", "local"]

  created_at:
    type: string
    format: date-time
    description: "ISO 8601 timestamp when environment was created"

  description:
    type: string
    description: "Optional description of the environment"

  ruby_versions:
    type: array
    description: "Ruby versions to use in this environment"
    items:
      type: string
      pattern: "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$"
    minItems: 1

  # Docker-specific properties
  image_variants:
    type: array
    description: "Docker image variants (docker type only)"
    items:
      type: string
      enum: ["slim", "alpine", "bullseye"]

  build_args:
    type: object
    description: "Docker build arguments (docker type only)"
    additionalProperties:
      type: string

  run_args:
    type: object
    description: "Docker run arguments (docker type only)"
    additionalProperties:
      type: string

  # ASDF-specific properties
  auto_install:
    type: boolean
    description: "Automatically install missing Ruby versions (asdf type only)"
    default: true

  global_gems:
    type: array
    description: "Global gems to install (asdf type only)"
    items:
      type: string

  # Local-specific properties
  ruby_path:
    type: string
    description: "Path to Ruby executable (local type only)"

  bundle_path:
    type: string
    description: "Path to bundle executable (local type only)"

  env_vars:
    type: object
    description: "Environment variables to set (local type only)"
    additionalProperties:
      type: string

# Conditional validation based on environment type
allOf:
  - if:
      properties:
        type:
          const: "docker"
    then:
      required:
        - ruby_versions
      properties:
        image_variants:
          minItems: 1
        build_args: true
        run_args: true
      not:
        anyOf:
          - required: ["auto_install"]
          - required: ["global_gems"]
          - required: ["ruby_path"]
          - required: ["bundle_path"]
          - required: ["env_vars"]

  - if:
      properties:
        type:
          const: "asdf"
    then:
      required:
        - ruby_versions
      properties:
        auto_install: true
        global_gems: true
      not:
        anyOf:
          - required: ["image_variants"]
          - required: ["build_args"]
          - required: ["run_args"]
          - required: ["ruby_path"]
          - required: ["bundle_path"]
          - required: ["env_vars"]

  - if:
      properties:
        type:
          const: "local"
    then:
      properties:
        ruby_path: true
        bundle_path: true
        env_vars: true
      not:
        anyOf:
          - required: ["ruby_versions"]
          - required: ["image_variants"]
          - required: ["build_args"]
          - required: ["run_args"]
          - required: ["auto_install"]
          - required: ["global_gems"]

examples:
  - name: "docker-ruby33"
    type: "docker"
    created_at: "2024-01-15T10:30:00Z"
    description: "Docker environment with Ruby 3.3"
    ruby_versions: ["3.3"]
    image_variants: ["slim", "alpine"]
    build_args: {}
    run_args: {}

  - name: "asdf-multi"
    type: "asdf"
    created_at: "2024-01-15T10:30:00Z"
    description: "ASDF environment with multiple Ruby versions"
    ruby_versions: ["3.2.8", "3.3.8"]
    auto_install: true
    global_gems: ["bundler", "rake"]

  - name: "local-dev"
    type: "local"
    created_at: "2024-01-15T10:30:00Z"
    description: "Local development environment"
    ruby_path: "/usr/local/bin/ruby"
    bundle_path: "/usr/local/bin/bundle"
    env_vars:
      RUBY_GC_HEAP_GROWTH_FACTOR: "1.1"
