# Configuration for CI/GitHub Actions - Memory-safe settings
# Only runs small data sizes to avoid memory constraints

data_sizes:
  - small

formats:
  - xml
  - json
  - yaml
  - toml

iterations:
  small: 20
  medium: 5
  large: 2

# Disable memory profiling in CI to reduce memory usage
memory_profiling: false

# Reduce warmup iterations for faster CI
warmup_iterations: 2
