# Configuration for comprehensive benchmarks - Full testing with all data sizes
# Used by Docker script for complete performance analysis

data_sizes:
  - small
  - medium
  - large

formats:
  - xml
  - json
  - yaml
  - toml

iterations:
  small: 20
  medium: 5
  large: 2

# Enable memory profiling for comprehensive analysis
memory_profiling: true

# Standard warmup iterations
warmup_iterations: 3

# Enable streaming benchmarks where supported
streaming_benchmarks: true

# Generate detailed reports
detailed_reports: true
