# Configuration for short benchmarks - Minimal memory usage for CI runners
# Designed for Windows and Ubuntu runners with limited memory

data_sizes:
  - small
  - medium

formats:
  - xml
  - json
  - yaml
  - toml

iterations:
  small: 5
  medium: 2
  large: 1

# Disable memory profiling to reduce memory usage
memory_profiling: false

# Minimal warmup iterations
warmup_iterations: 2

# Disable streaming benchmarks to reduce complexity
streaming_benchmarks: false

# Disable detailed reports to save memory
detailed_reports: false
