---
name: docker-ruby-3.1
kind: docker
created_at: '2025-06-13T15:18:43+08:00'
ruby_build_tag: "3.1.6"
description: Docker environment for Ruby 3.1 benchmarks
docker:
  image: 'ruby:3.1-slim'
  dockerfile: '../../docker/Dockerfile.ubuntu'
