---
name: docker-ruby-3.2
kind: docker
created_at: '2025-06-13T15:18:43+08:00'
ruby_build_tag: "3.2.4"
description: Docker environment for Ruby 3.2 benchmarks
docker:
  image: 'ruby:3.2-slim'
  dockerfile: '../../docker/Dockerfile.ubuntu'
