---
name: docker-ruby-3.4
kind: docker
created_at: '2025-06-13T15:18:43+08:00'
ruby_build_tag: "3.4.1"
description: Docker environment for Ruby 3.4 benchmarks
docker:
  image: 'ruby:3.4-slim'
  dockerfile: '../../docker/Dockerfile.ubuntu'
